development:
  adapter: postgresql
  database: sqlizer_dev
  pool: 5
  timeout: 5000
  encoding: utf8
  username: andrew

test: &test
  adapter: postgresql
  database: sqlizer_test
  pool: 5
  timeout: 5000
  encoding: utf8

#production:
#  adapter: postgresql
#  database: heroku_2ea99196f0f6155
#  pool: 5
#  timeout: 5000
#  encoding: utf8

cucumber:
  <<: *test
